markdown: redcarpet
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true

redcarpet:
    extensions:
        - with_toc_data
        - hard_wrap
        - no_intra_emphasis
        - tables
        - fenced_code_blocks
        - autolink

blog:
    name: THINK
    description: Cogito ergo sum
    title: I think therefore I am
    url: wangyinfeng.github.io

comments:
    provider: duoshuo
    duoshuo:
        short_name: thinkwang

author:
    name: Leo
    email: wang.batman@gmail.com
    weibo: http://www.weibo.com/u/1619196553
    github: https://github.com/wangyinfeng
    logo: /res/img/logo.jpg
